In [2]:
import pandas as pd

In [3]:
# 24년 자료라 크게 의미가 없음
df1 = pd.read_excel('./data/서울시 자치구 (목적별) CCTV 설치현황_241231.xlsx', header = 3)
df1.rename(columns={'소 계':'범죄예방및수사계', '어린이\n보호구역':'어린이보호구역', '공원·놀이터':'공원,놀이터', '쓰레기\n무단투기':'쓰레기무단투기','Unnamed: 8':'시설안전,화재예방','Unnamed: 9':'교통단속','Unnamed: 10':'교통정보수집,분석','Unnamed: 11':'기타목적','Unnamed: 2':'총계','Unnamed: 1':'시군구'}, inplace = True)
df1.drop(df1.columns[0],axis=1,inplace = True)
df1.fillna(value = 0, inplace = True)
df1[df1.columns[1:]] = df1.iloc[:,1:].astype(int)
df1[:26]

,시군구,총계,범죄예방및수사계,방범,어린이보호구역,"공원,놀이터",쓰레기무단투기,"시설안전,화재예방",교통단속,"교통정보수집,분석",기타목적
0,자치구,113273,99758,74807,8704,15417,830,4482,8648,18,367
1,종로구,2339,2154,1779,105,270,0,52,133,0,0
2,중구,3118,2567,2132,76,297,62,221,330,0,0
3,용산구,3609,3202,2669,162,371,0,5,402,0,0
4,성동구,4638,4084,2994,422,429,239,115,439,0,0
5,광진구,4636,4370,3102,642,561,65,174,92,0,0
6,동대문,3846,3602,2777,309,484,32,1,229,0,14
7,중랑구,5392,5009,4336,141,521,11,79,304,0,0
8,성북구,4906,4479,3362,453,664,0,74,335,18,0
9,강북구,3584,3430,2881,355,194,0,49,105,0,0
10,도봉구,2808,2623,1807,194,622,0,71,114,0,0
11,노원구,4105,3694,2117,358,1113,106,252,159,0,0
12,은평구,5683,5057,3922,150,985,0,255,371,0,0
13,서대문,4218,3438,2447,132,859,0,359,421,0,0
14,마포구,3809,3662,2868,227,527,40,0,147,0,0
15,양천구,4854,4464,2918,840,706,0,0,198,0,192
16,강서구,3874,3733,2816,302,594,21,0,141,0,0
17,구로구,5694,4909,3498,583,787,41,318,467,0,0
18,금천구,3458,3252,2487,266,453,46,4,191,0,11
19,영등포,5133,4500,3742,287,471,0,5,613,0,15
20,동작구,3664,3322,2290,403,609,20,134,73,0,135
21,관악구,6614,4907,3606,235,919,147,956,751,0,0
22,서초구,6036,3916,2896,203,817,0,883,1237,0,0
23,강남구,8352,7267,5385,1111,771,0,270,815,0,0
24,송파구,4665,4022,2698,480,844,0,205,438,0,0
25,강동구,4238,4095,3278,268,549,0,0,143,0,0

In [10]:
df2 = pd.read_excel('./data/서울시 자치구 (범죄예방 수사용) CCTV 설치현황_241231.xlsx', header = 2)
df2.drop(columns=list(df2.columns[:2]) + list(df2.columns[3:11]) + list(df2.columns[12:]),axis=1,inplace = True)
df2.rename(columns={'2023년':'범죄예방수사용','구분':'시군구'}, inplace = True)
df2 = df2[:26]
df2['범죄예방수사용'] = df2['범죄예방수사용'].astype(int)
df2

     시군구  범죄예방수사용
0      계    86810
1    종로구     1872
2     중구     2157
3    용산구     2897
4    성동구     3871
5    광진구     3421
6   동대문구     3077
7    중랑구     4163
8    성북구     4216
9    강북구     3191
10   도봉구     2196
11   노원구     2613
12   은평구     4369
13  서대문구     3117
14   마포구     3015
15   양천구     4064
16   강서구     3397
17   구로구     4265
18   금천구     2978
19  영등포구     3987
20   동작구     2656
21   관악구     4210
22   서초구     3343
23   강남구     6829
24   송파구     3471
25   강동구     3435

In [11]:
df3 = pd.read_excel('./data/서울시 자치구 (연도별) CCTV 설치현황_241231.xlsx', header = 2)
df3['2023년계'] = df3[df3.columns[4:13]].sum(axis = 1)
df3.drop(columns=list(df3.columns[:2]) + list(df3.columns[3:14]),axis=1,inplace = True)
df3.rename(columns={'2023년계':'2023년총CCTV','구분':'시군구'}, inplace = True)
df3['시군구'] = df3['시군구'].str.replace(' ','')
df3['2023년총CCTV'] = df3['2023년총CCTV'].astype(int)
df3[:26]

     시군구  2023년총CCTV
0      계       96270
1    종로구        2017
2     중구        2525
3    용산구        2980
4    성동구        4434
5    광진구        3682
6   동대문구        3268
7    중랑구        4537
8    성북구        3945
9    강북구        3504
10   도봉구        2233
11   노원구        2753
12   은평구        5062
13  서대문구        3799
14   마포구        3237
15   양천구        4271
16   강서구        3590
17   구로구        4376
18   금천구        3173
19  영등포구        4560
20   동작구        2895
21   관악구        5589
22   서초구        5292
23   강남구        7013
24   송파구        3986
25   강동구        3549

In [12]:
df_concat = df2.merge(df3, on='시군구')
df_concat

     시군구  범죄예방수사용  2023년총CCTV
0      계    86810       96270
1    종로구     1872        2017
2     중구     2157        2525
3    용산구     2897        2980
4    성동구     3871        4434
5    광진구     3421        3682
6   동대문구     3077        3268
7    중랑구     4163        4537
8    성북구     4216        3945
9    강북구     3191        3504
10   도봉구     2196        2233
11   노원구     2613        2753
12   은평구     4369        5062
13  서대문구     3117        3799
14   마포구     3015        3237
15   양천구     4064        4271
16   강서구     3397        3590
17   구로구     4265        4376
18   금천구     2978        3173
19  영등포구     3987        4560
20   동작구     2656        2895
21   관악구     4210        5589
22   서초구     3343        5292
23   강남구     6829        7013
24   송파구     3471        3986
25   강동구     3435        3549